version: '3.7'

services:
  web:
    build: ./
    command: uvicorn policyguru.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src/:/usr/src/policyguru/
    ports:
      - 8002:8000

volumes:
  data: