# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: policy-sentry

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  stage: stage
  region: us-east-2

custom:
  pythonRequirements:
    dockerizePip: true
    zip: true
    layer:
      name: policy-sentry-layer
      description: Layer for Policy Sentry API
      compatibleRuntimes:
        - python3.6
        - python3.7
        - python3.8
  siteName: policy-site-sls
  s3Sync:
  - bucketName: policy-site-sls
    localDir: static

# you can overwrite defaults here
functions:
  write_policy:
    handler: lambdas.write_policy.handler.write_policy
    description: "Lambda for Policy Sentry's write policy command"
    events:
      - http:
          path: write
          method: post
    layers:
      - {Ref: PythonRequirementsLambdaLayer}
  scan_policy:
    handler: lambdas.cloudsplaining_scan_policy.handler.cloudsplaining_scan_policy
    description: "Scan a policy file with Cloudsplaining"
    events:
      - http:
          path: scan
          method: post
    layers:
      - {Ref: PythonRequirementsLambdaLayer}
  query_resources:
    handler: lambdas.query_resources.handler.query_resources
    description: "Lambda for Policy Sentry's query ARN table command"
    events:
      - http:
          path: query/resources
          method: get
    layers:
      - {Ref: PythonRequirementsLambdaLayer}
  query_conditions:
    handler: lambdas.query_conditions.handler.query_conditions
    description: "Lambda for Policy Sentry's query conditions table command"
    events:
      - http:
          path: query/conditions
          method: get
    layers:
      - {Ref: PythonRequirementsLambdaLayer}
  query_actions:
    handler: lambdas.query_actions.handler.query_actions
    description: "Lambda for Policy Sentry's query actions table command"
    events:
      - http:
          path: query/actions
          method: get
    layers:
      - {Ref: PythonRequirementsLambdaLayer}
  policy_write:
    handler: lambdas.write_policy.handler.ui_response_handler
    events:
      - http:
          path: call_policy
          method: post
    layers:
      - {Ref: PythonRequirementsLambdaLayer}

resources:
  Resources:
    StaticSite:
      Type: AWS::S3::Bucket
      Properties:
        AccessControl: PublicRead
        BucketName: ${self:custom.siteName}
        WebsiteConfiguration:
          IndexDocument: index.html
    StaticSiteS3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: StaticSite
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: "*"
              Action:
                - s3:GetObject
              Resource:
                Fn::Join: [
                  "", [
                  "arn:aws:s3:::",
                  {
                    "Ref": "StaticSite"
                  },
                  "/*"
                ]
                ]

plugins:
  - serverless-python-requirements
  - serverless-s3-sync