# .github/workflows/test.yml

name: continuous-integration

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install aws-sam-cli

#     - run: invoke test.format
#     - run: invoke test.lint

      - name: Run unit tests
        run: invoke unit.pytest

      - name: Run security test
        run: invoke test.security

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Validate SAM Template
        run: invoke integration.sam-validate

      - name: Invoke individual lambda functions
        run: invoke integration.sam-invoke
